name: Node.js Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - run: npm ci
    - run: npm publish --access public